# Generated by Django 3.1.6 on 2021-02-22 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test_table',
            new_name='Testtable',
        ),
    ]
