# Generated by Django 3.1.6 on 2021-03-01 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210226_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForeignKeyExample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('testtable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.testtable')),
            ],
        ),
    ]
