# Generated by Django 3.1.6 on 2021-03-01 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_foreignkeyexample'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Testtable',
            new_name='Test',
        ),
    ]
