# Generated by Django 3.1.6 on 2021-03-01 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20210301_0928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foreignkeyexample',
            old_name='testtable',
            new_name='test',
        ),
        migrations.AddField(
            model_name='foreignkeyexample',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
